# From the three dog night song: "joy to the world (jermiah was a bullfrog)"
puts "joy to the world"
puts "All the boys and girls"
#puts "Joy to the fishes in the deep blue sea"
puts "Joy to you and me"